### ISSUE TITLE
Spinning Bot Zombie Games

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1262]
Reproduce:
- Join 1.9 lobby
- Join a bot
- Select a map you do not have
- Start the game
- When the prompt to download missing map, either cancel or hit okay on the prompt

Notice:
- You are disconnected from the game, but there is still a zombie player playing in the bot, and the game will just spin through rounds
- You can reconnect to the game, but there is no way to stop the bot unless you kill all of the client processes

**Comment by DanVanAtta** [comment]
Fixed with: https://github.com/triplea-game/triplea/pull/1264

**Comment by DanVanAtta** [comment]
Still seems to be a problem...

**Comment by RoiEXLab** [comment]
My thoughs about why this problem still persists.
First question is, if you updated the lobby after this PR was merged... If not try that.
Since adding breakpoints doesn't do anything, I'm assuming that most of this code is executed server side.
`game.shutdown()` does nothing while `game.isGameOver()` returns/is false. Maybe thats the reson for it not to work...
If remove this if statement inside shutdown has side effects, we might need to overload this method with a boolean param which enables this check per default. Or we copy past all code inside shutdow() and we use that instead...

Thoughts @DanVanAtta ?

**Comment by ron-murhammer** [comment]
@DanVanAtta Is this still unresolved and a blocker for releasing 1.9?

**Comment by RoiEXLab** [comment]
@ron-murhammer I don't think it's a blocker - it's more like a high priority bug... (Whenever the client's computer shuts down the server remains the same)

**Comment by RoiEXLab** [comment]
@DanVanAtta @ron-murhammer I know what the problem is now... After a lot of debugging I found out, that every time you join the lobby the startup-frame is hidden, but not closed. Whenever we hit "join game" a completely new java process is created creating an entirely new startup frame instead of reusing the current one. When we close the lobby window the old process is shutdown, but the newly created thread still continues existing for whatever reason...
I think this shouldn't take too long to fix...

**Comment by RoiEXLab** [comment]
#1273 has a fix!
