### ISSUE TITLE
2.6 Refresh maps-list/maps/ only 173 listed out of currently 315 repositories

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#12647]
https://triplea-game.org/maps-list/maps/ says 173 maps (Find view -1=173)

https://github.com/orgs/triplea-maps says 315 repositories 

maps-list/maps needs to be refreshed to match.

Dan I think this one is yours?

**Comment by Cernelius** [comment]
@TheDog-GH It's normal that the repositories are more (they include currently non-supported map-skins too), though I'm surprised that there are actually as many as 142 of them not being available maps.

**Comment by TheDog-GH** [comment]
@Cernelius  Ah yes, they will not match, thanks!

With my new powers of access to some of TripleA, I guess that 
https://github.com/triplea-game/triplea-game.github.io/tree/master/_maps

this update was ran 2 years ago and mainly Roger has been adding maps over the years, but Im new to this and my deductions might be wrong.

**Comment by Cernelius** [comment]
Yeah @RogerCooper's been adding tons. I wonder whether he intends some of these to remain in the repository but outside download list or he plans eventually to add them all to it. For example, "alexander350".

**Comment by TheDog-GH** [comment]
Last time I chatted to Roger about this he was not going to bother with 2.5s
https://github.com/triplea-game/triplea/blob/master/triplea_maps.yaml
because its so flaky, so outside of the current 2.6 downloads as its based off 2.5

However he did say that he was making them 2.6 Download ready by including a map.yml file like alexander350

**Comment by RogerCooper** [comment]
I have only a few maps left to upload to Github. Then I will starting reviewing the repositories and them triplea_maps.yaml when appropriate. (I will try to screen out superseded, duplicate and unplayable mods).

**Comment by DanVanAtta** [comment]
Barring any kinks, there are some updates that should resolve this issue:

(1) download-all-maps script is invoked daily. [Added a cronjob](https://github.com/triplea-game/infrastructure/commit/71ce3b92beeb59036192073fb44507576554e0a9)

I'm not sure it'll run 100% smooth, TBD.

(2) [bots restart automatically when a game ends](https://github.com/triplea-game/infrastructure/commit/9a482d20f4ef7a77918b922146c96ca714df50a6#diff-a198ee917784e8b72db3c09501d540ed8f1e2cb80a38123bf2f757d957c7b1e4R18
). Instead of going back to staging screen, the bot halts & the system restarts it automatically. Bots, on-startup, read new maps. Without this, there was the other problem of how to get bots to read the new maps after they have been updated.


In sum - map updates should flow every day and will be picked up on bot restart (which is now whenever any game ends)

**Comment by TheDog-GH** [comment]
Having left it a couple of days, this is still not working?
Is the Cronjob running daily?

Still finds 173 maps
https://triplea-game.org/maps-list/maps/ says 173 maps (Find view -1=173)

**Comment by Cernelius** [comment]
@TheDog-GH I don't understand what is requested here.

Those are the maps in download list, so their number should match the number of maps in that list, not necessarily the number of maps in the repository (beside the fact that the repository contains map-skins too, so it would not match even if all maps are listed).

**Comment by Cernelius** [comment]
Also, I'm not sure why we are talking about bots. This feature was not about bots until @DanVanAtta introduced them. Am I missing something?

**Comment by DanVanAtta** [comment]
@Cernelius  good point, I confused this issue with #12517 

The process for updating the maps on the website is certainly in trouble since we will be changing how maps are indexed. The update process from triplea_maps.yaml  to website was explicitly shut down back in 2022 in anticipation of having the system be reworked.

For reference, this SHA: 9350ca253744f0d3e4d9f0f5cadff54e8c288a7c

The open questions are whether to actually restore this update process (and if we don't, that implies we'd remove the 'maps' page). Second question, is how & when to do the updates. 

As-is, I don't know if any efforts are worthwhile here compared to focusing on solving the longer term issue.

**Comment by TheDog-GH** [comment]
My 2p is to replace it with a static page, with 5-10 chosen maps, maybe from here
https://forums.triplea-game.org/topic/3741/curated-best-top-maps-triplea-guides

With suitable text to show off TripleA and that its maps can do history, fantasy & Sci-Fi.

**Comment by DanVanAtta** [comment]
Not a bad thought.  Some other possibilities: (1) Github does provide a web API for listing repositories, we could bring back the map-splitter script with that as the data source instead  'triplea_maps.yaml' .(2) similar to 1, except use the maps server which will have a similar API that provides a list of maps - perhaps easier to parse.

**Comment by RogerCooper** [comment]
There are Github repositories which do not contain any scenarios. These seem to be from abandoned projects.

There seems to be some confusion in terminology. I use the following terms:

Mod - A folder on Github or your local computer that contains all the files needed to play one (or more scenarios)

Scenario - A specific entry showing up on the menu that defines a specific playable game

Map - The graphic and text files that define the game's on-screen map. In older versions of TripleA, the map could be defined specifically to use another mod, now you need to copy the map files from the mod.

I am almost finished with posting my mod collection to Github. I was planning on adding the mods to triplea_maps.yaml, as that is the currently functional area,

**Comment by Cernelius** [comment]
@RogerCooper I'm almost certain that what you call "mod" is a "map" and what you call "map" is a "skin" (except that it comprises everything outside the "games" folder so for example sound files too).

No problem with "scenario" if you want to suggest that name, but of course that has been called "game".

**Comment by RogerCooper** [comment]
I would say that TripleA is a game. The use of 'map' is confusing as in common usage a map is representation of geography. TripleA uses maps, but a mod has lot more in it than just a map.

I am coming at this as long time board wargamer, where games have scenarios and sometimes multiple maps.

**Comment by Cernelius** [comment]
If we want to propose clarifications or changes of terminology and their adoption and documentation as official (documenting them somewhere in an official TripleA dictionary) so to better define the TripleA jargon in order to facilitate communication, I suppose that should be attempted in a dedicated discussion.

About
>There are Github repositories which do not contain any scenarios. These seem to be from abandoned projects.

are you sure that you are not looking at map-skins?

**Comment by Cernelius** [comment]
By the way, I still cannot understand what this issue is asking to be done. Like, what exactly is needed for this issue to be closed as completed? I'm at a loss.

**Comment by DanVanAtta** [comment]
Re: glossary

FWIW: https://github.com/triplea-game/triplea/blob/master/docs/development/glossary.md

But, it's worth keeping in mind that TripleA represents multiple [bounded context](https://martinfowler.com/bliki/BoundedContext.html). In other words, the word "map" really depends on who you are talking to & when. A player vs a map-maker vs a developer can all have three equally valid yet different answers.  

And moving right along...

The list of maps at: https://triplea-game.org/maps-list/maps/ , has not been updated for some time.
The ask is for it to be updated regularly.

At first glance, we could resurrect the "YAML splitter", but the file "triplea_maps.yaml" is due to be retired "very soon." That does not represent a long term solution.

So, we need to do something like add a once-a-day github action job that will do something similar as the YAML splitter, but instead needs to fetch its data from a web service call to either Github's webservice API, or one we provide via the "maps server". The latter is likely going to be easiest to avoid the issues of parsing data in a more elaborate manner. Specifically our own custom API can provide an endpoint that gives exactly the needed JSON, which in turn is very little parsing for the YAML splitter to do.
