### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1327]
As agreed upon in prior issues/conversations- unless there is a compatibility issue, please do not update to 1.9.0.1

Please keep updating the website download version to the latest once we have tested  that there are no compatibility issues.  We have dropped the concept of 'stable' and 'unstable' releases.

**Comment by DanVanAtta** [comment]
I recommend renaming this milestone to 'regression fixes' or similar...

**Comment by ron-murhammer** [comment]
@DanVanAtta Can you link to the new versioning conventions? I've already been releasing incremental builds to the website as I've fixed bugs (the main one was that no mac users could play lobby games).

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/blob/master/docs/admin/version_numbers.md

It was in wiki, wiki documentation was all moved to 'docs' folder. We still have a couple of wiki pages which I think are finally now useful + appropriate. https://github.com/triplea-game/triplea/issues/323 was where we hashed out the versioning

**Comment by DanVanAtta** [comment]
Frankly I'm happy so long as we dont' go back to 'stable' 'unstable'. Chopping off zero's is a bit idealistic at the moment, but I do believe we have a roadmap.

**Comment by ron-murhammer** [comment]
We aren't quite following that versioning as we still have the original 4 numbers + build number. That page also seems to indicate we'd be resetting the build number after each release which we aren't.

I'm not really following what you are getting at here. We are currently on 1.9.0.0.build#. We are continuously releasing incremental builds as we make fixes (as long as they are save game and lobby compatible, 1.9.0.0.higher_build#). I'm grouping issues to put into the next release which would be 1.9.0.1 unless we change our number scheme to go to only 3 + build and if we were gonna do that we should really have done it with 1.9 so it would have been 1.9.0.build# instead of 1.9.0.0.build#.

My thought is that the next 'release' 1.9.0.1 or 1.9.1 is primarily focused on fixing regression bugs but can include any features we are working on as well. It would benefit us to release a new version so that we don't have people continuing to report the same issues.
