### ISSUE TITLE
TripleA 2.7.14962 battle calculator has extra icons

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#13281]
There appears to be a problem with the battle calculator, see below and in the attached saved game
Using TripleA 2.7.14962
The game is 1941 Global Command Decision, latest version here
https://github.com/triplea-maps/1941_global_command_decision

Note the Germans have a duplicated HQ-Army, icons 11 & 12 and the Neutrals 2nd & 3rd Icons  are duplicated they are both Inf-Trained

[2025-4-12-1941-Global-Command-Decision.zip](https://github.com/user-attachments/files/19720031/2025-4-12-1941-Global-Command-Decision.zip)

![Image](https://github.com/user-attachments/assets/c85d60eb-106a-456b-a14b-9518faa0b71c)

This issues is on other maps, see below, there is an extra pink dove/flag icon for a neutral player called 'none' 
![Image](https://github.com/user-attachments/assets/b79e9963-69d1-4674-ac12-6817c5e9ea21)

**Comment by frigoref** [comment]
@TheDog-GH I already wasted some time to reproduce this, but I am giving up. Please provide a reproducible example with clear instructions, i.e. which map version is needed for the provided save game and which steps are performed (territory, units selected, buttons clicked to start battle calculator, etc.).
When I try to load the save game, I get this:

![Image](https://github.com/user-attachments/assets/5dc521c5-3e9c-47de-984d-69b5e8e4b10e)

When you write "This issues is on other maps", please always provide concrete examples and preferably also clear instructions for them.

**Comment by frigoref** [comment]
Fixed with PR [13298](https://github.com/triplea-game/triplea/pull/13298)

@TheDog-GH: Thanks for the details provided! Please retest and close this issue in case it got resolved.

**Comment by TheDog-GH** [comment]
@frigoref There does not appear to be a compiled version for me to retest, or is there?

**Comment by TheDog-GH** [comment]
This is still happening with TripleA-2.7.15032 

[2025-4-24-1941-Global-Command-Decision-G001.zip](https://github.com/user-attachments/files/19896869/2025-4-24-1941-Global-Command-Decision-G001.zip)

Load saved game above
Go to Northern Spain
Press Ctrl+B on Aragon to see the same image above


![Image](https://github.com/user-attachments/assets/2bfc57d2-96aa-49f3-bd1a-ee8b9d9d3238)

It also occurs Russia St Petersburg, not just an isolated occurrence.
