### ISSUE TITLE
Current Release is not supported

### ISSUE THREAD

**Issue by ryanmccarthypdx** [triplea-game/triplea#13519]
### Reproduction Steps

1. Go to triplea-game.org
2. Click on Download, which pulls 2.5.x
3. Have a problem, try to file a bug
4. Bug is autoclosed because it's not 2.7.

OR

1. go to github.com/triplea-game/triplea
2. Click on releases
3. Find latest release (not pre-release) which is 2.5.x

Either 2.7 needs to be released & wired up to the website, or support for 2.5.x should continue.

**Comment by DanVanAtta** [comment]
Is there an auto-closed issue that you would like looked at in specific?

**Comment by ryanmccarthypdx** [comment]
The specific issue _was_ solved by upgrading, so we are unblocked.  

The issue is that the folks I play by forum against aren't super familiar with github and expect the 'download' button on the website to take them to a supported version.  You shouldn't have to be a professional software engineer to use TripleA.

**Comment by beelee1** [comment]
@ryanmccarthypdx heh heh while I can relate to github frustration, I'm not a software Engineer either but can still get it to work :)

One can have the 2.5 stable and and a prerelease(s) installed at the same time. Check out @TheDog-GH https://forums.triplea-game.org/topic/3724/how-to-have-triplea-2-5-2-6-installed-at-the-same-time

A little extra work for the guys but ... :) learning can be fun while annoying at the same time :)

I think you do need 2.5 to play in the 2.5 lobby and then I imagine the pre fixes don't work on it. I'm not sure though, as I can get only get the 2.5 lobby using windows. But for Forum play, you be all dialed in. :)

What game you guys play ?

**Comment by ryanmccarthypdx** [comment]
I guess I don't understand the reluctance to tag 2.7 versions as 'released'.  If those are the only versions worthy of support, why not wire them up to the public website?

IMO we should be making TripleA more accessible to non-technical folks.

**Comment by TheDog-GH** [comment]
@ryanmccarthypdx 

It was the Devs intention to put stable versions of 2.7 on triplea-game.org but as I understand it, TripleA lobby does not support 2.7 and nor do the bots, so not ideal.

I glad you could help your friends through the process.
