### ISSUE TITLE
Branch Model of Infrastructure

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#4086]
Branch model & deployment strategy have some details here: https://github.com/triplea-game/infrastructure#deployments

A key implication of gitlab flow is that all changes flow through master before going to prod. For us 'master' is effectively 'qa', and that is saying in another way that any production changes first go to QA (AKA prerelease).

Questions for the group:
- Any questions on this topic?
- Is the documentation looking okay? (let's perhaps spend more time reviewing documentation updates and leave those PRs open so we can all read them)
- Should we add any additional environments to the flow? 
- Should we rename branch: 'master' to 'QA'?

**Comment by prastle** [comment]
@DanVanAtta  It is interesting to note that none have disappeared since the manual restart of the missing bots.

**Comment by prastle** [comment]
It appears they wipe out after 48 hrs.  Just a general observation.
Multiple restarts all week. @DanVanAtta  @ssoloff

**Comment by ssoloff** [comment]
@prastle Would you say that your bot is being used by players just as much as the standard bots?

**Comment by prastle** [comment]
It has had a few games I have joined one or two and watched it play on.
I never checked or counted to see if it has had as much use as the bots.  All I can say is it hasn't crashed.   I host my own when I play while leaving it running
But to be direct... most bots are empty often as well.

**Comment by prastle** [comment]
So since many empty bots why are they disappearing
?

**Comment by prastle** [comment]
Atm same bot 2 players round 4 60? hrs later

**Comment by prastle** [comment]
started a few hrs ago

**Comment by DanVanAtta** [comment]
> I think this broke down about a month ago because we had a hotfix that needed to be pushed to prod, but there were already a few commits on master that had not yet been pushed to prod, and those commits were incompatible with the current bot/lobby versions in prod.

@ssoloff  I would agree this is where the break-down occurred. In hind sight, we could have:
- upgraded version number in infrastructure to latest as soon as we merged breaking changes to triplea-game.
- verified those changes after they are merged to master and auto-deployed to prereleases
- merge master to prod
- restarted bots at our convenience if at all.
- merge 'hotfix' to master
- merge master to prod
- restart bots when needed to pick up hotfix change


> That led to cherry-picking some changes from master to prod for such hotfixes.

Indeed, direct merges to master means we've lost already, there should never be a need to cherry-pick to prod.

> That then further broke down to committing changes directly to prod to fix emergency issues. 

This is a concern that I think could potentially happen again if we are not diligent to get breaking changes pushed to prod. @RoiEXLab @ssoloff @ron-murhammer any thoughts of tracking those updates with a story-board? https://github.com/triplea-game/triplea/projects/5  Any such PRs we can mark as part of that project and then would have tracking as we stage and then push the updates to prod. 

> One question that needs to be resolved is what will be our process to deploy hotfixes into production when we can't merge master -> prod outright?

Always deploy changes to master then merge master to prod wholesale. If master can't be deployed, then roll back the game updates that were incompatible. In essence we should always have a deployable master. Master is always deployed to pre-prod, if master is broken then pre-prod is broken. IN those cases we should fix quickly or rollback and not leave pre-prod broken. If we have broken pre-prod, what business have we to deploy to prod?

**Comment by ron-murhammer** [comment]
@DanVanAtta I'm fine with the branch model if its actually functional. To my knowledge the pre-prod server still isn't working. Generally, changes are being reviewed and the 1-2 hour outage was a mistake but it was reviewed by another person so that isn't the issue. The main issue is that there are a lot of scripts and the documentation isn't complete enough to make it obvious how to do many of the necessary tasks.

**Comment by DanVanAtta** [comment]
pre-prod server being broken is ideally treated as stop-the-presses project blocker. We're not quite yet there. I'll note that master was auto-deployed there for a few months, but we are getting on the same page now..

The 1-2 hour outage was exacerbated by us being out of sync and the branch model not being clear, it was not the whole story though for sure. 

The branch model calls for changes to be merged to master, reviewed, then master is 'promoted' to prod and reviewed once more. 

> The main issue is that there are a lot of scripts and the documentation isn't complete enough to make it obvious how to do many of the necessary tasks.

Indeed; infrastructure is a lot of automation, it's most of loose bits and ends that were hanging around our installation steps that I had to reverse engineer. To some extent the scripting is the automation, the only updates needed to upgrade versions or deploy new bots or remove bots is to update the host_control.sh file. 

I don't know if more documentation is going to help; It would be helpful for me to know where there is confusion and clarity. Is the branch model at least clear? 

For other infrastructure questions, IMO a new issue thread would be easiest to tackle those topics, but we can get into those questions here too.

**Comment by DanVanAtta** [comment]
Summarizing open items here:
- clarify/discuss any remaining branch model topics that are still fuzzy
- ensure we have this documented/spend some time clarifying & cleaning up that documentation
- follow up with any remaining questions about infrastructure and fix up documentation  gaps (https://github.com/triplea-game/triplea/issues/4117)
